Repository Indiebay/indie-bay, pull requests merged in 2018-04, with the labels that each got.

#12 Adds a Few Custom Hats
  code/modules/clothing/head/indiebay_hats.dm
  icons/mob/onmob/indiebay_hats.dmi
Labels: ➕ Addition, 🎨 Sprites

#13 Finalizes Job Changes
  code/datums/outfits/jobs/science.dm
  code/game/antagonist/station/revolutionary.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/science.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/client/preference_setup/loadout/lists/gloves.dm
  maps/torch/icons/assignment_hud.dmi
  maps/torch/items/cards_ids.dm
  maps/torch/job/jobs.dm
  maps/torch/job/outfits.dm
  maps/torch/loadout/_defines.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/loadout/loadout_eyes.dm
  maps/torch/loadout/loadout_gloves.dm
  maps/torch/loadout/loadout_suit.dm
  maps/torch/loadout/loadout_uniform.dm
Labels: ➕ Addition, 🔩 Tweak

#17 Trust in the Rust!
  code/game/objects/effects/overlays.dm
  code/game/turfs/simulated/walls.dm
  code/modules/materials/materials.dm
  icons/effects/rust.dmi
Labels: ✔️ Ready for Review, ➕ Addition

#18 Toggles produces_heat in gun.dm from 1 to 0. Guns are no longer broken.
  code/modules/projectiles/gun.dm
Labels: 🔩 Tweak

#20 Nerfs the Bioprinter
  code/game/machinery/bioprinter.dm
Labels: travis pls, 🔩 Tweak

#22 Lifts many loadout restrictions, adds some new items to loadout
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/indiebay_hats.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/accessories/clothing.dm
  icons/mob/onmob/head.dmi
  icons/mob/onmob/indiebay_hats.dmi
  icons/mob/onmob/ties.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/ties.dmi
  maps/torch/loadout/_defines.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/loadout/loadout_eyes.dm
  maps/torch/loadout/loadout_gloves.dm
  maps/torch/loadout/loadout_head.dm
  maps/torch/loadout/loadout_shoes.dm
  maps/torch/loadout/loadout_suit.dm
  maps/torch/loadout/loadout_uniform.dm
  maps/torch/loadout/loadout_xeno.dm
  maps/torch/loadout/~defines.dm
Labels: 🔧 Fix, 🔩 Tweak

#23 Adds Podmorph humans and pod-printer;
  baystation12.dme
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/species/station/human_subspecies.dm
  code/modules/organs/internal/brain.dm
  code/modules/organs/internal/eyes.dm
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/organs/internal/liver.dm
  code/modules/organs/internal/lungs.dm
  code/modules/podprinter/printer.dm
  icons/mob/human_races/r_podsynth.dmi
  icons/mob/human_races/subspecies/r_podmorph.dmi
  icons/mob/pod_people.dmi
  icons/mob/podsynth.dmi
  icons/obj/podprinter.dmi
Labels: ➕ Addition

#21 Tweaks subspecies, and fixes gravity-adapted sprites.
  code/modules/mob/living/carbon/human/species/station/human_subspecies.dm
  icons/mob/human_races/subspecies/r_gravworlder.dmi
Labels: 🎨 Sprites, 🔩 Tweak

#24 Tweaks the ERT to fit them more to our lore.
  code/game/antagonist/outsider/ert.dm
  maps/torch/torch-6.dmm
Labels: ➖ Removal, 🔩 Tweak, 🗺️ Map

#27 ERT map changes
  maps/torch/torch-6.dmm
Labels: 🗺️ Map
